server:
    verbosity: 0
    use-syslog: no
    logfile: ""
    chroot: ""
    username: ""
    directory: "."
    pidfile: "unbound.pid"
    interface: 127.0.0.1@5302
    do-ip6: no
    access-control: 127.0.0.0/8 allow
    num-threads: 2
    so-reuseport: yes
    qname-minimisation: no
    cache-min-ttl: 0
    cache-max-ttl: 86400
    prefetch: no
    rrset-roundrobin: no
    msg-cache-size: 128m
    rrset-cache-size: 256m
    msg-cache-slabs: 4
    rrset-cache-slabs: 4
    harden-dnssec-stripped: no
    val-permissive-mode: yes
    module-config: "iterator"
    do-not-query-localhost: no
    local-zone: "test." nodefault
forward-zone:
    name: "."
    forward-addr: 127.0.0.1@5300
